spring:
  application:
    name: eureka-server
server:
  port: 8010
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8010/eureka/
  instance:
      prefer-ip-address: true
      instance-id: 127.0.0.1:8010

