server:
  port: 8012
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8010/eureka/,http://localhost:8009/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
     prefer-ip-address: true
     instance-id: 127.0.0.1:8012

spring:
  application:
    name: eureka-service.consumer
EUREKA-SERVICE.PRODUCER: #服务的id
    ribbon:
       NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #算法的实现类

#Hystrix的超时时间
hystrix:
   command:
     default:
         execution:
           isolation :
               thread :
                 timeoutInMilliseconds: 6000
#使用Feign之后ribbon的超时时长配置
ribbon:
  ReadTimeout: 40
  ConnectTimeout: 4
#ribbon:
 #  ConnectionTimeOut: 50000 #ribbon在500毫秒内没有建立连接就超时
  # ReadTimeOut: 20000      #ribbon在1s内没有响应就超时
#使用feign之后开启hystrix功能
feign:
   hystrix:
     enabled: true
