server:
  port: 8012
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8010/eureka/
  instance:
     prefer-ip-address: true
     instance-id: 127.0.0.1:8012
spring:
  application:
    name: eureka-service.consumer