eureka:
  client:
    service-url:
     defaultZone: http://localhost:8010/eureka/,http://localhost:8009/eureka/
    register-with-eureka: true
  instance:
    #prefer-ip-address: true
   # instance-id: 127.0.0.1:8015
    lease-expiration-duration-in-seconds: 30

    lease-renewal-interval-in-seconds: 30
spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/db_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
      name: eureka-service-producer
server:
  port: 8015
mybatis:
  type-aliases-package: com.eureka.entity

